network:
  loss:
    otype: Huber
  optimizer:
    otype: Ema
    decay: 0.95
    nested:
      otype: ExponentialDecay
      decay_start: 20000
      decay_interval: 10000
      decay_base: 0.33
      nested:
        otype: Adam
        learning_rate: 1e-2
        beta1: 0.9
        beta2: 0.99
        epsilon: 1e-15
        l2_reg: 1e-6
  encoding:
    otype: HashGrid
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 19
    base_resolution: 16
  network:
    otype: FullyFusedMLP
    activation: ReLU
    output_activation: None
    n_neurons: 64
    n_hidden_layers: 1
  dir_encoding:
    otype: Composite
    nested:
      - n_dims_to_encode: 3
        otype: SphericalHarmonics
        degree: 4
      - otype: Identity
        n_bins: 4
        degree: 4
  rgb_network:
    otype: FullyFusedMLP
    activation: ReLU
    output_activation: None
    n_neurons: 64
    n_hidden_layers: 2
# training_data: /home/mumu/uav-nerf-test/data/nerf/new_data_v2/transforms.json
training_data: /home/mumu/uav-nerf-test/output/test.json
load_snapshot: ~ 
save_snapshot: ~
test_transforms: ~
# screenshot_transforms: /home/mumu/uav-nerf-test/data/nerf/new_data_v2/transforms_1.json
screenshot_transforms: /home/mumu/uav-nerf-test/output/test.json
# screenshot_transforms: ~
screenshot: true
screenshot_spp: 1 #16
save_mesh: ~
marching_cubes_res: 256
width: 0
height: 0
n_steps: 2000
train_seconds: 1000
enable_depth_loading: true
depth_supervision_lambda: 1.0 # original depth loss
depth_optimize_density_grid: false
depth_optimize_ray_tracing: true
minimum_thickness_of_opaque_object_realunit: 0. # unit:meter
rays_per_batch: 4096 # default is 4096. we can enlarge it 32768 to due to many ray weill be empty
max_empty_samples_per_ray: 1
lower_limit_opaque_point_weight: 0.01 # weight = alpha*T, alpha = 1 - expf(-density * dt),  T*=(1-alpha)
max_samples_behind_surface: 10 #
empty_density_loss_scale: 0.
opaque_density_loss_scale: 0.0001
sharpen: 0
exposure: 0